#!/usr/bin/env python
# -*- coding: utf-8 -*-
u"""
sbt docで生成したscaladocのindex.htmlを開くと、
検索窓にフォーカスが移るようJavascriptを改変する。
コマンドライン引数にapiディレクトリのパスを指定する。
指定がなければ、カレントディレクトリ下のapiディレクトリを対象とする。
"""

import sys
import os.path
import traceback

class InvalidJSException(Exception):
    pass

if __name__ == '__main__':
    retcode = 0

    if len(sys.argv) >= 2:
        paths = sys.argv[1:]
    else:
        paths = ['./api']

    for path in paths:
        if not os.path.exists(path):
            sys.stderr.write('cannot find ' + path + '\n')
            retcode = 1
            continue
        try:
            js_path = os.path.join(path, 'lib/index.js')
            with open(js_path) as f:
                lines = f.readlines()
            for (i,l) in enumerate(lines):
                marker = "<input id='index-input'"
                if marker in l:
                    lines[i] = l.replace(marker, marker + " autofocus")
                    break
            else:
                msg = (js_path +
                       " does not generate input element for index search")
                raise InvalidJSException(msg)
            with open(js_path, 'w') as f:
                f.writelines(lines)
        except:
            traceback.print_exc()
            retcode = 1

    sys.exit(retcode)
